### ISSUE TITLE
Fix estimation window edge cases

### ISSUE THREAD

**Issue by kebrahim** [google-org/new-project-ny#166]
In certain cases (e.g. 2 hr - 2 hr; "a few moments") the estimation window displayed on the FE doesn't make sense

**Comment by itssumertime** [comment]
I'm still digging into this but I think it's because we are using both the JS "moment" library as well as React's "Moment" library (imported from "react-moment"), and converting between the two.

Also, we should define how exactly we want this displayed. We could do "1 hr 20 min - 1 hr 40 min" or we can round and do "1 hr 20 - 2 hr" or "1 - 2 hr" etc. Since the times displayed below it are exact, we probably want to keep the exact, but then for times that are just slightly above an hour, do we instead want to make them into minutes? "80 - 120 mins" or do we still want "50 mins - 1 hr 10 mins", where we list it out properly with the hour?

**Comment by itssumertime** [comment]
I figured out why this happens: https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/02-fromnow/

45-89 mins are rounded to "1 hour"  while 90 mins rounds to "2 hours". 

Working on the fix but the conclusion from discussions is that we'll change:
--"a few seconds" -> "1 min" since seconds is never relevant or accurate
--"1 hour to 1 hour" -> "42 mins to 1 hour 17 mins", meaning that we'll use the exact generated values rather than any rounding (not even rounding to "45 mins")
