### ISSUE TITLE
Google Java format presubmit is consistently failing

### ISSUE THREAD

**Issue by kebrahim** [google-org/new-project-ny#76]
![image](https://user-images.githubusercontent.com/2208244/80974909-676b3200-8def-11ea-951a-2a21f37e772e.png)

issue with "axel-op/googlejavaformat-action@v2.0.0" library

configured here: https://github.com/google-org/new-project-ny/blob/master/.github/workflows/linting.yml#L26

**Comment by tariqajyusuf** [comment]
The source library pulls the latest version of google-java-format which released a new version [3 days ago](https://github.com/google/google-java-format/releases/tag/google-java-format-1.8). This update changed the minimum supported version to JDK 11.

Looking at a [recent failure log](https://github.com/google-org/new-project-ny/pull/77/checks?check_run_id=643106457) and the screenshot above. The issue seems to be that the container is trying to run a Java 11 binary with Java 8. The attached [virtual environment list](https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md) from GitHub seems to indicate that it in fact includes JDK 11 but the default is set to version 8.

I'm looking into how to set the default version to 11.
